brew "asciinema"
brew "python@3.14"
brew "awscli"
brew "bat"
brew "glib"
brew "pycparser"
brew "cffi"
brew "cloc"
brew "coreutils"
brew "curl"
brew "docker-completion"
brew "exiftool"
brew "fd"
brew "harfbuzz"
brew "ffmpeg-full"
brew "findutils"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "homeshick"
brew "htop"
brew "imagemagick-full"
brew "inlyne"
brew "jnv"
brew "jq"
brew "just"
brew "lesspipe"
brew "libyaml"
brew "mas"
brew "mise"
brew "mysql-client"
brew "nkf"
brew "nmap"
brew "pkgconf"
brew "pngquant"
brew "poppler"
brew "procs"
brew "pv"
brew "pwgen"
brew "reattach-to-user-namespace"
brew "resvg"
brew "ripgrep"
brew "sevenzip"
brew "tartufo"
brew "tbls"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "watch"
brew "yazi"
brew "zoxide"
brew "zplug"
cask "1password"
cask "1password-cli"
cask "adguard"
cask "appcleaner"
cask "blender"
cask "chatgpt"
cask "claude"
cask "claude-code@latest"
cask "discord"
cask "font-hackgen"
cask "font-symbols-only-nerd-font"
cask "font-zed-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "gpg-suite"
cask "hammerspoon"
cask "hhkb"
cask "inkscape"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "kicad"
cask "nani"
cask "netnewswire"
cask "ngrok"
cask "notion"
cask "obsidian"
cask "postman"
cask "qlmarkdown"
cask "readdle-spark"
cask "rectangle"
cask "slack"
cask "steam"
cask "suspicious-package"
cask "tailscale-app"
cask "the-unarchiver"
cask "zed"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Obsidian Web Clipper", id: 6720708363
mas "Pages", id: 409201541
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
