# tap repositories
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'

# completions
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'docker-machine-completion'
brew 'zsh-completions'

# dependencies 
## plantuml depends java
cask 'java'

# packages
brew 'ansible'
brew 'autojump'
brew 'colordiff'
brew 'coreutils'
brew 'findutils'
brew 'ghq'
brew 'gist'
brew 'git-flow'
brew 'git-now'
brew 'git'
brew 'gnu-tar'
brew 'go'
brew 'heroku'
brew 'htop-osx'
brew 'imagemagick'
brew 'jq'
brew 'lesspipe', args: ['with-syntax-highlighting']
brew 'nkf'
brew 'node'
brew 'optipng'
brew 'peco'
brew 'plantuml'
brew 'pngquant'
brew 'pwgen'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'source-highlight'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'zsh', args: ['disable-etcdir']

# packages from cask
## fonts
cask 'font-source-han-code-jp'

# apps
cask 'appcleaner'
cask 'atom'
cask 'cathode'
cask 'docker'
cask 'duet'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'kitematic'
cask 'slack'
cask 'the-unarchiver'
cask 'vagrant'
cask 'virtualbox'

## quicklook
cask 'betterzipql'
cask 'epubquicklook'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'quicklookase'
cask 'suspicious-package'
cask 'webpquicklook'
